### ISSUE TITLE
有人知道这个code怎么算出来的吗

### ISSUE THREAD

**Issue by liuziqi** [codingChengxians/zmyy#8]
![Inked8X(N`7HFSP79}@_SVK1`24L](https://user-images.githubusercontent.com/68654324/147718321-d447e23c-14be-4713-af4a-df555b078d08.jpg)

**Comment by Iprotagonist** [comment]
没找到，我也卡这步了

**Comment by Z980** [comment]
> ![Inked8X(N7HFSP79}@_SVK124L](https://user-images.githubusercontent.com/68654324/147718321-d447e23c-14be-4713-af4a-df555b078d08.jpg)
wx.login
